### ISSUE TITLE
react on returncode instead of "space" on toggler

### ISSUE THREAD

**Issue by christianhaessler** [Shihira/gnome-extension-quicktoggler#10]
I think it would be a more effective way to react on returncodes for "detector" instead of listening to the output.

>  If the output consists of whitespaces or is empty, the detection result is false. Otherwise it is true. The switch will then be switch on or off automatically.

For example if the returncode is 0 the detection result ist true otherwise (if the returncode != 0 ) the detection result is false.

In my case i wrote a script to activate/deactivate some shortcuts for using windows in virtual box. Of course i am writing some output to the shell if i start the script:

```
christian@hugo:~$ win_keys.sh start
Parameter is start. Going to disable the defined windows keys.
```
```
christian@hugo:~$ win_keys.sh status
Windows keys are disabled in gnome (rc 0)
```
```
christian@hugo:~$ win_keys.sh stop
Parameter is stop. Going to enable the defined windows keys.
```
```
christian@hugo:~$ win_keys.sh status
Windows keys are enabled in gnome (rc 1)
```

**Comment by Shihira** [comment]
IMHO it is usually easy to turn a returncode into texts and hard to turn texts into a returncode, isn't it?

I understand that you want to keep your scripts neat but there is no need to keep the configuration file neat in any way. In your case I recommend you to write in this way:

```
win_keys.sh status > /dev/null && echo yes
# Or use grep directly
win_keys.sh status | grep enabled
```

**Comment by christianhaessler** [comment]
hey shihira,
good point/idea. This is a simple workaround.
thanks
