### ISSUE TITLE
Not available on Gnome 3.20

### ISSUE THREAD

**Issue by Id2ndR** [Shihira/gnome-extension-quicktoggler#2]
Please add compatibility to Fedora 24 (Gnome 3.20).

I just added 3.20 in metadata.json and it's working normally.

**Comment by Shihira** [comment]
@Id2ndR Thanks for your report.

But I am afraid you have to wait for a week or so until I update my system for tests. For some special reason I need stability recently so I dare not update right now.

In this period I am wondering If you'd like to do me a favour, to alter `metadata.json` and append `"3.20"` to `shell-version` array on your own, and report to me again if any exceptions occur.

Sorry for keeping you waiting.

**Comment by Shihira** [comment]
@Id2ndR I update the code: 1f2c01323bafecefe565cc2bd04e015563c25e4e. See if it meets your demand. A copy has been uploaded to extensions.gnome.org already and is pending for review.

**Comment by Id2ndR** [comment]
Warning : updating the extension through Gnome delete the existing entries.json :(

**Comment by Shihira** [comment]
@Id2ndR Oh so sorry about that. That's really awkward. I didn't expect that. I think I'd better deprecate the default entries.json.

Can you open a new issue about this?
